### ISSUE TITLE
Soporte 32 bits

### ISSUE THREAD

**Issue by Indziaki** [TransbankDevelopers/transbank-pos-sdk-dotnet#37]
Hola, me gustaría saber si soporta la arquitectura de 32 bits, ya que cuando intento ejecutar el proyecto me da error de que no encuentra el archivo TransbankPosSDK.dll.

Gracias.

**Comment by afiebig** [comment]
Hola @Indziaki la librería en C no soporta 32bits. Sin embargo, si tienes un equipo de 32bits puedes intentar compilar tu propia versión siguiendo las instrucciones en el readme de ese proyecto.
